// components/Phone3D.tsx
// @ts-nocheck
"use client";

import { useEffect, useRef } from "react";
import * as THREE from "three";

interface Phone3DProps {
  screenshotSrc: string;
}

export default function Phone3D({ screenshotSrc }: Phone3DProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const cleanupRef = useRef<(() => void) | null>(null);

  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;

    const width = container.clientWidth;
    const height = container.clientHeight;

    // --- Renderer ---
    const renderer = new THREE.WebGLRenderer({
      antialias: true,
      alpha: true,
    });
    renderer.setSize(width, height);
    renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
    renderer.toneMapping = THREE.ACESFilmicToneMapping;
    renderer.toneMappingExposure = 1.4;
    renderer.shadowMap.enabled = true;
    renderer.shadowMap.type = THREE.PCFSoftShadowMap;
    container.appendChild(renderer.domElement);

    // --- Scene & Camera ---
    const scene = new THREE.Scene();
    const camera = new THREE.PerspectiveCamera(30, width / height, 0.1, 100);
    camera.position.set(0, 0, 5.5);

    // --- Lighting ---
    scene.add(new THREE.AmbientLight(0xffffff, 0.5));

    const keyLight = new THREE.DirectionalLight(0xffffff, 1.5);
    keyLight.position.set(2, 3, 5);
    keyLight.castShadow = true;
    keyLight.shadow.mapSize.width = 1024;
    keyLight.shadow.mapSize.height = 1024;
    keyLight.shadow.camera.near = 0.5;
    keyLight.shadow.camera.far = 15;
    keyLight.shadow.camera.left = -2;
    keyLight.shadow.camera.right = 2;
    keyLight.shadow.camera.top = 3;
    keyLight.shadow.camera.bottom = -3;
    keyLight.shadow.radius = 6;
    scene.add(keyLight);

    const fillLight = new THREE.DirectionalLight(0x8899cc, 0.3);
    fillLight.position.set(-3, 1, 3);
    scene.add(fillLight);

    // --- Shadow catcher plane (invisible, receives shadow) ---
    const shadowGeo = new THREE.PlaneGeometry(4, 6);
    const shadowMat = new THREE.ShadowMaterial({ opacity: 0.35 });
    const shadowPlane = new THREE.Mesh(shadowGeo, shadowMat);
    shadowPlane.position.z = -0.15;
    shadowPlane.receiveShadow = true;
    scene.add(shadowPlane);

    // No glow light — just keep key/fill for shine

    // --- Phone dimensions (thin, modern) ---
    const W = 0.95;
    const H = 1.95;
    const D = 0.08;
    const R = 0.14; // corner radius
    const BEZEL = 0.025; // very thin bezel

    // --- Rounded rect shape helper ---
    function roundedRect(w, h, r) {
      const s = new THREE.Shape();
      const hw = w / 2, hh = h / 2;
      s.moveTo(-hw + r, -hh);
      s.lineTo(hw - r, -hh);
      s.quadraticCurveTo(hw, -hh, hw, -hh + r);
      s.lineTo(hw, hh - r);
      s.quadraticCurveTo(hw, hh, hw - r, hh);
      s.lineTo(-hw + r, hh);
      s.quadraticCurveTo(-hw, hh, -hw, hh - r);
      s.lineTo(-hw, -hh + r);
      s.quadraticCurveTo(-hw, -hh, -hw + r, -hh);
      return s;
    }

    // --- Body ---
    const bodyGeo = new THREE.ExtrudeGeometry(roundedRect(W, H, R), {
      steps: 1,
      depth: D,
      bevelEnabled: true,
      bevelThickness: 0.012,
      bevelSize: 0.012,
      bevelSegments: 5,
    });
    bodyGeo.center();

    const bodyMat = new THREE.MeshPhysicalMaterial({
      color: 0x1c1c1e,
      metalness: 0.95,
      roughness: 0.2,
      clearcoat: 0.8,
      clearcoatRoughness: 0.15,
    });
    const body = new THREE.Mesh(bodyGeo, bodyMat);
    body.castShadow = true;

    // --- Screen (rounded corners matching iPhone) ---
    const scrW = W - BEZEL * 2;
    const scrH = H - BEZEL * 2;
    const scrR = R - BEZEL; // screen corner radius matches body minus bezel

    const screenShape = roundedRect(scrW, scrH, scrR);
    const screenGeo = new THREE.ShapeGeometry(screenShape);

    // Compute UVs for the rounded shape so the texture maps correctly
    const pos = screenGeo.attributes.position;
    const uvs = new Float32Array(pos.count * 2);
    for (let i = 0; i < pos.count; i++) {
      uvs[i * 2] = (pos.getX(i) + scrW / 2) / scrW;
      uvs[i * 2 + 1] = (pos.getY(i) + scrH / 2) / scrH;
    }
    screenGeo.setAttribute('uv', new THREE.BufferAttribute(uvs, 2));

    const tex = new THREE.TextureLoader().load(screenshotSrc);
    tex.colorSpace = THREE.SRGBColorSpace;

    const screenMat = new THREE.MeshBasicMaterial({ map: tex, toneMapped: false });
    const screen = new THREE.Mesh(screenGeo, screenMat);
    screen.position.z = D / 2 + 0.013;

    // --- Screen glass overlay (subtle reflection, also rounded) ---
    const glassGeo = new THREE.ShapeGeometry(roundedRect(scrW, scrH, scrR));
    const glassMat = new THREE.MeshPhysicalMaterial({
      color: 0xffffff,
      transparent: true,
      opacity: 0.03,
      roughness: 0.05,
      metalness: 0,
      clearcoat: 1,
    });
    const glass = new THREE.Mesh(glassGeo, glassMat);
    glass.position.z = D / 2 + 0.014;

    // --- Dynamic Island ---
    const diW = 0.26, diH = 0.065;
    const diShape = new THREE.Shape();
    const dir = diH / 2;
    diShape.absarc(diW / 2 - dir, 0, dir, -Math.PI / 2, Math.PI / 2, false);
    diShape.absarc(-diW / 2 + dir, 0, dir, Math.PI / 2, -Math.PI / 2, false);
    const diGeo = new THREE.ShapeGeometry(diShape);
    const diMat = new THREE.MeshBasicMaterial({ color: 0x000000 });
    const di = new THREE.Mesh(diGeo, diMat);
    di.position.set(0, scrH / 2 - 0.06, D / 2 + 0.0145);

    // --- Side buttons ---
    const btnMat = new THREE.MeshPhysicalMaterial({
      color: 0x2a2a2e,
      metalness: 0.95,
      roughness: 0.15,
    });

    // Power button (right side)
    const powerGeo = new THREE.BoxGeometry(0.014, 0.19, 0.05);
    const powerBtn = new THREE.Mesh(powerGeo, btnMat);
    powerBtn.position.set(W / 2 + 0.014, 0.35, 0);

    // Volume buttons (left side, close together)
    const volGeo = new THREE.BoxGeometry(0.014, 0.13, 0.05);
    const volUp = new THREE.Mesh(volGeo, btnMat);
    volUp.position.set(-W / 2 - 0.014, 0.36, 0);
    const volDown = new THREE.Mesh(volGeo, btnMat);
    volDown.position.set(-W / 2 - 0.014, 0.16, 0);

    // Mute switch (above volume buttons)
    const muteGeo = new THREE.BoxGeometry(0.014, 0.08, 0.04);
    const muteSwitch = new THREE.Mesh(muteGeo, btnMat);
    muteSwitch.position.set(-W / 2 - 0.014, 0.58, 0);

    // --- Camera module (back) ---
    const camHousingGeo = new THREE.ExtrudeGeometry(roundedRect(0.35, 0.35, 0.06), {
      depth: 0.015, bevelEnabled: true,
      bevelThickness: 0.005, bevelSize: 0.005, bevelSegments: 3,
    });
    const camHousingMat = new THREE.MeshPhysicalMaterial({
      color: 0x1c1c1e, metalness: 0.9, roughness: 0.2,
    });
    const camHousing = new THREE.Mesh(camHousingGeo, camHousingMat);
    camHousing.position.set(-0.15, 0.6, -D / 2 - 0.02);

    const lensGeo = new THREE.CylinderGeometry(0.045, 0.045, 0.02, 24);
    const lensMat = new THREE.MeshPhysicalMaterial({
      color: 0x0a0a12, metalness: 0.5, roughness: 0.05, clearcoat: 1,
    });
    const lensRingMat = new THREE.MeshPhysicalMaterial({
      color: 0x333338, metalness: 0.95, roughness: 0.1,
    });
    const lensRingGeo = new THREE.TorusGeometry(0.048, 0.005, 8, 32);

    function makeLens(x, y) {
      const lens = new THREE.Mesh(lensGeo, lensMat);
      lens.rotation.x = Math.PI / 2;
      lens.position.set(x, y, -D / 2 - 0.03);
      const ring = new THREE.Mesh(lensRingGeo, lensRingMat);
      ring.position.set(x, y, -D / 2 - 0.022);
      return [lens, ring];
    }

    const [l1, r1] = makeLens(-0.22, 0.68);
    const [l2, r2] = makeLens(-0.08, 0.68);
    const [l3, r3] = makeLens(-0.15, 0.52);

    // --- Assemble ---
    const phone = new THREE.Group();
    phone.add(body, screen, glass, di, powerBtn, volUp, volDown, muteSwitch);
    phone.add(camHousing, l1, r1, l2, r2, l3, r3);

    phone.rotation.x = 0.08;
    phone.rotation.y = -0.12;
    scene.add(phone);

    // --- State ---
    let targetRotX = 0.08, targetRotY = -0.12;
    let currentRotX = 0.08, currentRotY = -0.12;
    let animId = 0;

    const onMouseMove = (e) => {
      if (gyroActive) return; // gyro takes priority on mobile
      const mx = (e.clientX / window.innerWidth - 0.5) * 2;
      const my = (e.clientY / window.innerHeight - 0.5) * 2;
      targetRotY = mx * 0.35;
      targetRotX = -my * 0.15;
      keyLight.position.x = 2 + mx * 1.5;
      keyLight.position.y = 3 - my * 1;
    };
    window.addEventListener("mousemove", onMouseMove);

    // --- Gyroscope tilt for mobile ---
    let gyroActive = false;
    let gyroCleanup: (() => void) | null = null;

    const onDeviceOrientation = (e: DeviceOrientationEvent) => {
      if (e.gamma == null || e.beta == null) return;
      gyroActive = true;
      const mx = Math.max(-1, Math.min(1, e.gamma / 30));
      const my = Math.max(-1, Math.min(1, (e.beta - 45) / 30));
      targetRotY = mx * 0.35;
      targetRotX = -my * 0.15;
      keyLight.position.x = 2 + mx * 1.5;
      keyLight.position.y = 3 - my * 1;
    };

    function enableGyro() {
      window.addEventListener("deviceorientation", onDeviceOrientation);
    }

    // Try gyro directly (works on Android + older iOS)
    const DOE = (window as any).DeviceOrientationEvent;
    if (DOE && typeof DOE.requestPermission === "function") {
      // iOS 13+ — request on tap of the phone mockup itself
      const requestOnTap = () => {
        DOE.requestPermission().then((state: string) => {
          if (state === "granted") enableGyro();
        }).catch(() => {});
      };
      container.addEventListener("touchend", requestOnTap, { once: true });
      gyroCleanup = () => {
        container.removeEventListener("touchend", requestOnTap);
        window.removeEventListener("deviceorientation", onDeviceOrientation);
      };
    } else if (DOE) {
      // Android / non-permission browsers — just enable
      enableGyro();
      gyroCleanup = () => window.removeEventListener("deviceorientation", onDeviceOrientation);
    }

    // Visibility-aware render loop — pause when off-screen
    let isVisible = false;
    const visObserver = new IntersectionObserver(
      (entries) => {
        isVisible = entries[0]?.isIntersecting ?? false;
        if (isVisible && !animId) animate();
      },
      { threshold: 0 }
    );
    visObserver.observe(container);

    function animate() {
      if (!isVisible) { animId = 0; return; }
      animId = requestAnimationFrame(animate);
      currentRotX += (targetRotX - currentRotX) * 0.06;
      currentRotY += (targetRotY - currentRotY) * 0.06;
      phone.rotation.x = currentRotX;
      phone.rotation.y = currentRotY;
      renderer.render(scene, camera);
    }
    animate();

    const onResize = () => {
      const w = container.clientWidth;
      const h = container.clientHeight;
      camera.aspect = w / h;
      camera.updateProjectionMatrix();
      renderer.setSize(w, h);
    };
    window.addEventListener("resize", onResize, { passive: true });

    cleanupRef.current = () => {
      window.removeEventListener("mousemove", onMouseMove);
      window.removeEventListener("resize", onResize);
      gyroCleanup?.();
      visObserver.disconnect();
      isVisible = false;
      cancelAnimationFrame(animId);
      renderer.dispose();
      if (container.contains(renderer.domElement)) {
        container.removeChild(renderer.domElement);
      }
    };

    return () => cleanupRef.current?.();
  }, [screenshotSrc]);

  return (
    <div
      ref={containerRef}
      style={{ width: "100%", height: "100%", position: "absolute", inset: 0 }}
    />
  );
}

// new_app/components/Phone3D.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref, watch } from 'vue'
import * as THREE from 'three'
import { useSharedMouse, delayedSampleAt } from '../composables/useSharedMouse'

const props = withDefaults(defineProps<{
  screenshotSrc: string
  tiltDelayMs?: number
  screenTransition?: boolean
  screenTransitionDirection?: 'up' | 'down' | 'left' | 'right'
  // Skip shadow casting and lower DPR cap for cheaper rendering on background
  // phones where the visual fidelity loss is imperceptible.
  lite?: boolean
}>(), {
  tiltDelayMs: 0,
  screenTransition: false,
  screenTransitionDirection: 'up',
  lite: false,
})

const containerRef = ref<HTMLDivElement | null>(null)
let cleanup: (() => void) | null = null
let updateTexture: ((src: string) => void) | null = null
let initObserver: IntersectionObserver | null = null
let initialized = false

function initPhone() {
  const container = containerRef.value
  if (!container || initialized) return

  initialized = true

  const width = Math.max(container.clientWidth, 1)
  const height = Math.max(container.clientHeight, 1)

  const isLite = props.lite
  const renderer = new THREE.WebGLRenderer({
    antialias: true,
    alpha: true,
  })
  renderer.setSize(width, height)
  // Background phones cap at 1.25 DPR — they're at scale 0.6-0.7 and lower
  // opacity, so the resolution drop is invisible. Main phone keeps DPR 2.
  renderer.setPixelRatio(Math.min(window.devicePixelRatio, isLite ? 1.25 : 2))
  renderer.toneMapping = THREE.ACESFilmicToneMapping
  renderer.toneMappingExposure = 1.4
  renderer.shadowMap.enabled = !isLite
  renderer.shadowMap.type = THREE.VSMShadowMap
  container.appendChild(renderer.domElement)

  const scene = new THREE.Scene()
  const camera = new THREE.PerspectiveCamera(30, width / height, 0.1, 100)
  camera.position.set(0, 0, 3.92)

  scene.add(new THREE.AmbientLight(0xffffff, 0.5))

  const keyLight = new THREE.DirectionalLight(0xffffff, 1.5)
  keyLight.position.set(2, 3, 5)
  keyLight.castShadow = !isLite
  if (!isLite) {
    keyLight.shadow.mapSize.width = 1024
    keyLight.shadow.mapSize.height = 1024
    keyLight.shadow.camera.near = 0.5
    keyLight.shadow.camera.far = 15
    keyLight.shadow.camera.left = -2
    keyLight.shadow.camera.right = 2
    keyLight.shadow.camera.top = 3
    keyLight.shadow.camera.bottom = -3
    keyLight.shadow.radius = 6
  }
  scene.add(keyLight)

  const fillLight = new THREE.DirectionalLight(0x8899cc, 0.3)
  fillLight.position.set(-3, 1, 3)
  scene.add(fillLight)

  if (!isLite) {
    const shadowPlane = new THREE.Mesh(
      new THREE.PlaneGeometry(4, 6),
      new THREE.ShadowMaterial({ opacity: 0.35 }),
    )
    shadowPlane.position.z = -0.15
    shadowPlane.receiveShadow = true
    scene.add(shadowPlane)
  }

  const W = 0.95
  const H = 1.95
  const D = 0.08
  const R = 0.14
  const BEZEL = 0.025

  function roundedRect(w: number, h: number, r: number) {
    const shape = new THREE.Shape()
    const hw = w / 2
    const hh = h / 2

    shape.moveTo(-hw + r, -hh)
    shape.lineTo(hw - r, -hh)
    shape.quadraticCurveTo(hw, -hh, hw, -hh + r)
    shape.lineTo(hw, hh - r)
    shape.quadraticCurveTo(hw, hh, hw - r, hh)
    shape.lineTo(-hw + r, hh)
    shape.quadraticCurveTo(-hw, hh, -hw, hh - r)
    shape.lineTo(-hw, -hh + r)
    shape.quadraticCurveTo(-hw, -hh, -hw + r, -hh)

    return shape
  }

  const bodyGeo = new THREE.ExtrudeGeometry(roundedRect(W, H, R), {
    steps: 1,
    depth: D,
    bevelEnabled: true,
    bevelThickness: 0.012,
    bevelSize: 0.012,
    bevelSegments: 5,
  })
  bodyGeo.center()

  const bodyMat = new THREE.MeshPhysicalMaterial({
    color: 0x1c1c1e,
    metalness: 0.95,
    roughness: 0.2,
    clearcoat: 0.8,
    clearcoatRoughness: 0.15,
  })
  const body = new THREE.Mesh(bodyGeo, bodyMat)
  body.castShadow = !isLite

  const scrW = W - BEZEL * 2
  const scrH = H - BEZEL * 2
  const scrR = R - BEZEL
  const screenGeo = new THREE.ShapeGeometry(roundedRect(scrW, scrH, scrR))
  const pos = screenGeo.attributes.position as THREE.BufferAttribute
  const uvs = new Float32Array(pos.count * 2)

  for (let i = 0; i < pos.count; i += 1) {
    uvs[i * 2] = (pos.getX(i) + scrW / 2) / scrW
    uvs[i * 2 + 1] = (pos.getY(i) + scrH / 2) / scrH
  }

  screenGeo.setAttribute('uv', new THREE.BufferAttribute(uvs, 2))

  function configureScreenTexture(texture: THREE.Texture) {
    texture.colorSpace = THREE.SRGBColorSpace
    texture.wrapS = THREE.ClampToEdgeWrapping
    texture.wrapT = THREE.ClampToEdgeWrapping
    texture.repeat.set(1, 1)
    texture.offset.set(0, 0)
  }

  type ScreenImage = HTMLImageElement | HTMLCanvasElement

  const screenTextureCanvas = document.createElement('canvas')
  screenTextureCanvas.width = 393
  screenTextureCanvas.height = 852
  const screenTextureCtx = screenTextureCanvas.getContext('2d')
  if (screenTextureCtx) {
    screenTextureCtx.fillStyle = '#050505'
    screenTextureCtx.fillRect(0, 0, screenTextureCanvas.width, screenTextureCanvas.height)
  }

  const imageCache = new Map<string, Promise<HTMLImageElement>>()
  let currentSrc = props.screenshotSrc
  let currentScreenImage: ScreenImage | null = null
  let textureRequestId = 0
  let screenTransition: {
    from: ScreenImage
    to: ScreenImage
    direction: 'up' | 'down' | 'left' | 'right'
    start: number
    duration: number
  } | null = null

  function imageSize(image: ScreenImage) {
    if (image instanceof HTMLImageElement) {
      return {
        width: image.naturalWidth || image.width,
        height: image.naturalHeight || image.height,
      }
    }

    return {
      width: image.width,
      height: image.height,
    }
  }

  function drawScreenImage(image: ScreenImage, x = 0, y = 0) {
    if (!screenTextureCtx) return

    const { width: imageW, height: imageH } = imageSize(image)
    const canvasW = screenTextureCanvas.width
    const canvasH = screenTextureCanvas.height
    const scale = Math.max(canvasW / imageW, canvasH / imageH)
    const drawW = imageW * scale
    const drawH = imageH * scale
    const drawX = (canvasW - drawW) / 2 + x
    const drawY = (canvasH - drawH) / 2 + y

    screenTextureCtx.drawImage(image, drawX, drawY, drawW, drawH)
  }

  function drawStaticScreen(image: ScreenImage | null = currentScreenImage) {
    if (!screenTextureCtx || !image) return

    screenTextureCtx.clearRect(0, 0, screenTextureCanvas.width, screenTextureCanvas.height)
    drawScreenImage(image)
    activeTexture.needsUpdate = true
  }

  function snapshotScreen() {
    const snapshot = document.createElement('canvas')
    snapshot.width = screenTextureCanvas.width
    snapshot.height = screenTextureCanvas.height
    snapshot.getContext('2d')?.drawImage(screenTextureCanvas, 0, 0)
    return snapshot
  }

  function loadScreenImage(src: string) {
    const cached = imageCache.get(src)
    if (cached) return cached

    const promise = new Promise<HTMLImageElement>((resolve, reject) => {
      const image = new Image()
      image.decoding = 'async'
      image.onload = () => resolve(image)
      image.onerror = reject
      image.src = src
    })

    imageCache.set(src, promise)
    return promise
  }

  function renderScreenTransition(now: number) {
    if (!screenTransition || !screenTextureCtx) return

    const progress = Math.min(1, (now - screenTransition.start) / screenTransition.duration)
    const eased = 1 - Math.pow(1 - progress, 3)
    const isHorizontal = screenTransition.direction === 'left' || screenTransition.direction === 'right'
    const offset = (isHorizontal ? screenTextureCanvas.width : screenTextureCanvas.height)
      * eased
      * (screenTransition.direction === 'up' || screenTransition.direction === 'left' ? -1 : 1)
    const x = isHorizontal ? offset : 0
    const y = isHorizontal ? 0 : offset

    screenTextureCtx.clearRect(0, 0, screenTextureCanvas.width, screenTextureCanvas.height)
    drawScreenImage(screenTransition.to)
    drawScreenImage(screenTransition.from, x, y)

    const edge = isHorizontal
      ? screenTransition.direction === 'left'
        ? screenTextureCanvas.width + x
        : x
      : screenTransition.direction === 'up'
        ? screenTextureCanvas.height + y
        : y
    const maxEdge = isHorizontal ? screenTextureCanvas.width : screenTextureCanvas.height
    if (edge > 0 && edge < maxEdge) {
      const gradient = isHorizontal
        ? screenTextureCtx.createLinearGradient(edge - 24, 0, edge + 24, 0)
        : screenTextureCtx.createLinearGradient(0, edge - 24, 0, edge + 24)
      gradient.addColorStop(0, 'rgba(0,0,0,0)')
      gradient.addColorStop(0.5, 'rgba(0,0,0,0.32)')
      gradient.addColorStop(1, 'rgba(0,0,0,0)')
      screenTextureCtx.fillStyle = gradient
      if (isHorizontal) {
        screenTextureCtx.fillRect(edge - 24, 0, 48, screenTextureCanvas.height)
      } else {
        screenTextureCtx.fillRect(0, edge - 24, screenTextureCanvas.width, 48)
      }
    }

    activeTexture.needsUpdate = true

    if (progress >= 1) {
      currentScreenImage = screenTransition.to
      screenTransition = null
      drawStaticScreen()
    }
  }

  let activeTexture = new THREE.CanvasTexture(screenTextureCanvas)
  configureScreenTexture(activeTexture)
  const screenMat = new THREE.MeshBasicMaterial({ map: activeTexture, toneMapped: false })

  const screen = new THREE.Mesh(
    screenGeo,
    screenMat,
  )
  screen.position.z = D / 2 + 0.013

  const glass = new THREE.Mesh(
    new THREE.ShapeGeometry(roundedRect(scrW, scrH, scrR)),
    new THREE.MeshPhysicalMaterial({
      color: 0xffffff,
      transparent: true,
      opacity: 0.03,
      roughness: 0.05,
      metalness: 0,
      clearcoat: 1,
    }),
  )
  glass.position.z = D / 2 + 0.014

  const diW = 0.26
  const diH = 0.065
  const diShape = new THREE.Shape()
  const diR = diH / 2
  diShape.absarc(diW / 2 - diR, 0, diR, -Math.PI / 2, Math.PI / 2, false)
  diShape.absarc(-diW / 2 + diR, 0, diR, Math.PI / 2, -Math.PI / 2, false)

  const dynamicIsland = new THREE.Mesh(
    new THREE.ShapeGeometry(diShape),
    new THREE.MeshBasicMaterial({ color: 0x000000 }),
  )
  dynamicIsland.position.set(0, scrH / 2 - 0.06, D / 2 + 0.0145)

  const btnMat = new THREE.MeshPhysicalMaterial({
    color: 0x2a2a2e,
    metalness: 0.95,
    roughness: 0.15,
  })

  const powerBtn = new THREE.Mesh(new THREE.BoxGeometry(0.014, 0.19, 0.05), btnMat)
  powerBtn.position.set(W / 2 + 0.014, 0.35, 0)

  const volUp = new THREE.Mesh(new THREE.BoxGeometry(0.014, 0.13, 0.05), btnMat)
  volUp.position.set(-W / 2 - 0.014, 0.36, 0)

  const volDown = new THREE.Mesh(new THREE.BoxGeometry(0.014, 0.13, 0.05), btnMat)
  volDown.position.set(-W / 2 - 0.014, 0.16, 0)

  const muteSwitch = new THREE.Mesh(new THREE.BoxGeometry(0.014, 0.08, 0.04), btnMat)
  muteSwitch.position.set(-W / 2 - 0.014, 0.58, 0)

  const camHousing = new THREE.Mesh(
    new THREE.ExtrudeGeometry(roundedRect(0.35, 0.35, 0.06), {
      depth: 0.015,
      bevelEnabled: true,
      bevelThickness: 0.005,
      bevelSize: 0.005,
      bevelSegments: 3,
    }),
    new THREE.MeshPhysicalMaterial({
      color: 0x1c1c1e,
      metalness: 0.9,
      roughness: 0.2,
    }),
  )
  camHousing.position.set(-0.15, 0.6, -D / 2 - 0.02)

  const lensGeo = new THREE.CylinderGeometry(0.045, 0.045, 0.02, 24)
  const lensMat = new THREE.MeshPhysicalMaterial({
    color: 0x0a0a12,
    metalness: 0.5,
    roughness: 0.05,
    clearcoat: 1,
  })
  const lensRingGeo = new THREE.TorusGeometry(0.048, 0.005, 8, 32)
  const lensRingMat = new THREE.MeshPhysicalMaterial({
    color: 0x333338,
    metalness: 0.95,
    roughness: 0.1,
  })

  function makeLens(x: number, y: number) {
    const lens = new THREE.Mesh(lensGeo, lensMat)
    lens.rotation.x = Math.PI / 2
    lens.position.set(x, y, -D / 2 - 0.03)

    const ring = new THREE.Mesh(lensRingGeo, lensRingMat)
    ring.position.set(x, y, -D / 2 - 0.022)

    return [lens, ring]
  }

  const [l1, r1] = makeLens(-0.22, 0.68)
  const [l2, r2] = makeLens(-0.08, 0.68)
  const [l3, r3] = makeLens(-0.15, 0.52)

  const phone = new THREE.Group()
  phone.add(body, screen, glass, dynamicIsland, powerBtn, volUp, volDown, muteSwitch)
  phone.add(camHousing, l1, r1, l2, r2, l3, r3)
  phone.rotation.x = 0.08
  phone.rotation.y = -0.12
  scene.add(phone)

  loadScreenImage(currentSrc)
    .then((image) => {
      if (currentSrc !== props.screenshotSrc) return
      currentScreenImage = image
      drawStaticScreen(image)
      renderer.render(scene, camera)
    })
    .catch(() => {})

  updateTexture = (src: string) => {
    if (src === currentSrc) return

    const requestId = textureRequestId + 1
    textureRequestId = requestId
    const previousImage = screenTransition ? snapshotScreen() : currentScreenImage
    currentSrc = src

    loadScreenImage(src)
      .then((nextImage) => {
        if (requestId !== textureRequestId || src !== currentSrc) return

        if (!props.screenTransition || !previousImage || window.matchMedia('(prefers-reduced-motion: reduce)').matches) {
          currentScreenImage = nextImage
          screenTransition = null
          drawStaticScreen(nextImage)
          renderer.render(scene, camera)
          return
        }

        screenTransition = {
          from: previousImage,
          to: nextImage,
          direction: props.screenTransitionDirection,
          start: performance.now(),
          duration: 760,
        }

        if (isVisible && !animId) animate()
      })
      .catch(() => {})
  }

  let gyroActive = false
  let gyroCleanup: (() => void) | null = null
  let targetRotX = 0.08
  let targetRotY = -0.12
  let currentRotX = 0.08
  let currentRotY = -0.12
  let animId = 0
  let isVisible = false
  // Shared singleton — replaces a per-instance window mousemove listener.
  // animate() reads from sharedMouse.latest (delay = 0) or interpolates from
  // sharedMouse.samples (delay > 0), so behaviour matches the original to
  // within one rAF frame.
  const sharedMouse = useSharedMouse()

  function applyPointerTilt(mx: number, my: number) {
    targetRotY = mx * 0.35
    targetRotX = my * 0.15
    keyLight.position.x = 2 + mx * 1.5
    keyLight.position.y = 3 - my
  }

  const onDeviceOrientation = (event: DeviceOrientationEvent) => {
    if (event.gamma == null || event.beta == null) return

    gyroActive = true

    const mx = Math.max(-1, Math.min(1, event.gamma / 30))
    const my = Math.max(-1, Math.min(1, (event.beta - 45) / 30))

    applyPointerTilt(mx, my)
  }

  function enableGyro() {
    window.addEventListener('deviceorientation', onDeviceOrientation)
  }

  const deviceOrientation = window.DeviceOrientationEvent as (typeof DeviceOrientationEvent & {
    requestPermission?: () => Promise<PermissionState>
  }) | undefined

  if (deviceOrientation && typeof deviceOrientation.requestPermission === 'function') {
    const requestOnTap = () => {
      deviceOrientation.requestPermission?.()
        .then((state) => {
          if (state === 'granted') enableGyro()
        })
        .catch(() => {})
    }

    container.addEventListener('touchend', requestOnTap, { once: true })
    gyroCleanup = () => {
      container.removeEventListener('touchend', requestOnTap)
      window.removeEventListener('deviceorientation', onDeviceOrientation)
    }
  } else if (deviceOrientation) {
    enableGyro()
    gyroCleanup = () => window.removeEventListener('deviceorientation', onDeviceOrientation)
  }

  const animate = () => {
    if (!isVisible || document.hidden) {
      animId = 0
      return
    }

    animId = requestAnimationFrame(animate)
    if (!gyroActive) {
      const delay = Math.max(0, props.tiltDelayMs)
      if (delay > 0) {
        const delayed = delayedSampleAt(sharedMouse.samples, performance.now() - delay)
        if (delayed) applyPointerTilt(delayed.mx, delayed.my)
      } else if (sharedMouse.samples.length > 0) {
        // Skip until first real mouse event — otherwise (0,0) pulls the phone
        // away from its rest pose immediately on visibility.
        applyPointerTilt(sharedMouse.latest.mx, sharedMouse.latest.my)
      }
    }

    currentRotX += (targetRotX - currentRotX) * 0.06
    currentRotY += (targetRotY - currentRotY) * 0.06
    phone.rotation.x = currentRotX
    phone.rotation.y = currentRotY
    renderScreenTransition(performance.now())
    renderer.render(scene, camera)
  }

  const visObserver = new IntersectionObserver(
    (entries) => {
      isVisible = entries[0]?.isIntersecting ?? false
      if (isVisible && !animId && !document.hidden) animate()
    },
    { threshold: 0 },
  )
  visObserver.observe(container)

  const onDocumentVisibilityChange = () => {
    if (!document.hidden && isVisible && !animId) animate()
  }
  document.addEventListener('visibilitychange', onDocumentVisibilityChange)

  const applyResize = () => {
    const w = Math.max(container.clientWidth, 1)
    const h = Math.max(container.clientHeight, 1)

    camera.aspect = w / h
    camera.updateProjectionMatrix()
    renderer.setSize(w, h)
  }
  let resizeRaf = 0
  const onResize = () => {
    if (resizeRaf) return
    resizeRaf = requestAnimationFrame(() => {
      resizeRaf = 0
      applyResize()
    })
  }
  window.addEventListener('resize', onResize, { passive: true })

  cleanup = () => {
    window.removeEventListener('resize', onResize)
    if (resizeRaf) {
      cancelAnimationFrame(resizeRaf)
      resizeRaf = 0
    }
    document.removeEventListener('visibilitychange', onDocumentVisibilityChange)
    gyroCleanup?.()
    visObserver.disconnect()
    isVisible = false
    cancelAnimationFrame(animId)

    updateTexture = null
    activeTexture.dispose()
    renderer.dispose()

    scene.traverse((object) => {
      if (!(object instanceof THREE.Mesh)) return

      object.geometry.dispose()
      const materials = Array.isArray(object.material) ? object.material : [object.material]
      materials.forEach((material) => material.dispose())
    })

    if (container.contains(renderer.domElement)) {
      container.removeChild(renderer.domElement)
    }
  }
}

function initWhenNearViewport() {
  const container = containerRef.value
  if (!container) return

  initObserver = new IntersectionObserver(
    (entries) => {
      if (!entries[0]?.isIntersecting) return

      initObserver?.disconnect()
      initObserver = null
      initPhone()
    },
    { rootMargin: '600px 0px' },
  )

  initObserver.observe(container)
}

onMounted(initWhenNearViewport)
onBeforeUnmount(() => {
  initObserver?.disconnect()
  cleanup?.()
})

watch(
  () => props.screenshotSrc,
  (src) => {
    if (updateTexture) {
      updateTexture(src)
    } else {
      initPhone()
    }
  },
)
</script>

<template>
  <div ref="containerRef" class="phone-3d-mount" />
</template>
